In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Housing.csv")
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
# Q1.  Write a program to find the average price of houses grouped by the number of bedrooms. 
# Display the result in descending order of average price.

data.groupby("bedrooms")["price"].mean(numeric_only=True).sort_values(ascending=False)

bedrooms
5    5.819800e+06
4    5.729758e+06
3    4.954598e+06
6    4.791500e+06
2    3.632022e+06
1    2.712500e+06
Name: price, dtype: float64

In [4]:
#Q2. Create a program to calculate the total area of houses grouped by stories. 
# Display only the top 2 with the largest total area.
data.groupby("stories")["area"].sum(numeric_only=True).sort_values(ascending=False).head(2)

stories
1    1200790
2    1132153
Name: area, dtype: int64

In [5]:
#Q3.  Determine the maximum price of houses based on whether they have hotwaterheating or not. 
# Also display the data of both rows. 

data.groupby("hotwaterheating")["price"].max(numeric_only=True)

hotwaterheating
no     13300000
yes     9681000
Name: price, dtype: int64

In [6]:
#Q4.  Add a column named PricePerSqFt to calculate the price per square foot for each house. 
# Group the dataset by the number of floors and find the average PricePerSqFt for each group.

data["PricePerSqFt"] = data["price"] / data["area"]
data.groupby("stories")["PricePerSqFt"].mean(numeric_only=True)

stories
1     850.473821
2    1080.066043
3    1154.987392
4    1126.961447
Name: PricePerSqFt, dtype: float64

In [7]:
#Q5. Group the data by parking and count the total number of houses in each number of parking. Also sort in acsending order.
data.groupby("parking").size().sort_values(ascending=True)

parking
3     12
2    108
1    126
0    299
dtype: int64

In [8]:
#Q6.  Write a program to group houses based on the number of bathrooms and find the minimum, maximum, and average area (square feet) for each bathroom group.  

data.groupby("bathrooms")["area"].agg(["min", "max", "mean"], numeric_only=True)

            min    max         mean
bathrooms
1          1650  15600  4920.892768
2          1950  12090  5699.526316
3          2610  16200  6677.000000
4          8960   8960  8960.000000

In [9]:
#Q7. Perform all the attributes and methods of pandas groupby object on this dataset which are discussed in class and analyse the data.
grouped = data.groupby("bedrooms")
print(grouped.size())

bedrooms
1      2
2    136
3    300
4     95
5     10
6      2
dtype: int64

In [10]:
#Q8. Write a python program which display the name and data of the individual groups and performing groupby on furnishingstatus column of the dataset.

grouped_furnishing = data.groupby("furnishingstatus")
for name, group in grouped_furnishing:
    print(f"Group: {name}")
    print(group)

Group: furnished
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
8     9870000  8100         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
509   2590000  3600         2          2        2      yes        no      yes
512   2520000  3000         2          1        2      yes        no       no
522   2380000  2475         3          1        2      yes        no       no
523   2380000  2787         4          2        2      yes        no       no
543   1750000  2910         3          1        1       no        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
8                no             yes        2      yes        furnished
..              ...             ...      ...      ...              ...
509              no              no        1       no        furnished
512              no              no        0       no        furnished
522              no              no        0       no        furnished
523              no              no        0       no        furnished
543              no              no        0       no        furnished

     PricePerSqFt
0     1792.452830
1     1367.187500
3     1628.666667
4     1537.735849
8     1218.518519
..            ...
509    719.444444
512    840.000000
522    961.616162
523    853.964837
543    601.374570

[140 rows x 14 columns]
Group: semi-furnished
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
2    12250000  9960         3          2        2      yes        no      yes
5    10850000  7500         3          3        1      yes        no      yes
6    10150000  8580         4          3        4      yes        no       no
11    9681000  6000         4          3        2      yes       yes      yes
12    9310000  6550         4          2        2      yes        no       no
..        ...   ...       ...        ...      ...      ...       ...      ...
502   2660000  3480         2          1        1      yes        no       no
503   2660000  4000         3          1        1      yes        no       no
514   2485000  3000         3          1        2       no        no       no
527   2275000  1836         2          1        1       no        no      yes
541   1767150  2400         3          1        1       no        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
2                no              no        2      yes   semi-furnished
5                no             yes        2      yes   semi-furnished
6                no             yes        2      yes   semi-furnished
11              yes              no        2       no   semi-furnished
12               no             yes        1      yes   semi-furnished
..              ...             ...      ...      ...              ...
502              no              no        1       no   semi-furnished
503              no              no        0       no   semi-furnished
514              no              no        0       no   semi-furnished
527              no              no        0       no   semi-furnished
541              no              no        0       no   semi-furnished

     PricePerSqFt
2     1229.919679
5     1446.666667
6     1182.983683
11    1613.500000
12    1421.374046
..            ...
502    764.367816
503    665.000000
514    828.333333
527   1239.106754
541    736.312500

[227 rows x 14 columns]
Group: unfurnished
        price   area  bedrooms  bathrooms  stories mainroad guestroom  \
7    10150000  16200         5          3        2      yes        no
9     9800000   5750         3          2        4      yes       yes
16    9100000   6600         4          2        2      yes       yes
21    8680000   7155         3          2        1      yes       yes
28    8400000   7950         5          2        2      yes        no
..        ...    ...       ...        ...      ...      ...       ...
538   1890000   3649         2          1        1      yes        no
539   1855000   2990         2          1        1       no        no
540   1820000   3000         2          1        1      yes        no
542   1750000   3620         2          1        1      yes        no
544   1750000   3850         3          1        2      yes        no

    basement hotwaterheating airconditioning  parking prefarea  \
7         no              no              no        0       no
9         no              no             yes        1      yes
16       yes              no             yes        1      yes
21       yes              no             yes        2       no
28       yes             yes              no        2       no
..       ...             ...             ...      ...      ...
538       no              no              no        0       no
539       no              no              no        1       no
540      yes              no              no        2       no
542       no              no              no        0       no
544       no              no              no        0       no

    furnishingstatus  PricePerSqFt
7        unfurnished    626.543210
9        unfurnished   1704.347826
16       unfurnished   1378.787879
21       unfurnished   1213.137666
28       unfurnished   1056.603774
..               ...           ...
538      unfurnished    517.950123
539      unfurnished    620.401338
540      unfurnished    606.666667
542      unfurnished    483.425414
544      unfurnished    454.545455

[178 rows x 14 columns]