In [33]:
import pandas as pd
import numpy as np

In [34]:
data = pd.read_csv('StudentsPerformance.csv')
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
data.value_counts('race/ethnicity')
data.head()
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [36]:
data.rename(columns={'race/ethnicity':'groups'},inplace=True)
groups = data.groupby('groups') # This creates a groupby object named groups
print(groups) # This will print the groupby object, which is not very informative

<pandas.api.typing.DataFrameGroupBy object at 0x00000208E770C550>

In [37]:
for group,data in groups: # This way can be used to print that group data.. because it stores similiar as dictionary.
    print(group)
    print(data)

group A
     gender   groups parental level of education         lunch  \
3      male  group A          associate's degree  free/reduced
13     male  group A                some college      standard
14   female  group A             master's degree      standard
25     male  group A             master's degree  free/reduced
46   female  group A          associate's degree      standard
..      ...      ...                         ...           ...
974  female  group A                some college      standard
983  female  group A                some college      standard
985    male  group A                 high school      standard
988  female  group A            some high school  free/reduced
994    male  group A                 high school      standard

    test preparation course  math score  reading score  writing score
3                      none          47             57             44
13                completed          78             72             70
14                     none          50             53             58
25                     none          73             74             72
46                completed          55             65             62
..                      ...         ...            ...            ...
974                    none          54             63             67
983               completed          78             87             91
985                    none          57             51             54
988                    none          44             45             45
994                    none          63             63             62

[89 rows x 8 columns]
group B
     gender   groups parental level of education         lunch  \
0    female  group B           bachelor's degree      standard
2    female  group B             master's degree      standard
5    female  group B          associate's degree      standard
6    female  group B                some college      standard
7      male  group B                some college  free/reduced
..      ...      ...                         ...           ...
969  female  group B           bachelor's degree      standard
976    male  group B                some college  free/reduced
980  female  group B                 high school  free/reduced
982    male  group B            some high school      standard
991  female  group B            some high school      standard

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
2                      none          90             95             93
5                      none          71             83             78
6                 completed          88             95             92
7                      none          40             43             39
..                      ...         ...            ...            ...
969                    none          75             84             80
976               completed          60             62             60
980                    none           8             24             23
982               completed          79             85             86
991               completed          65             82             78

[190 rows x 8 columns]
group C
     gender   groups parental level of education         lunch  \
1    female  group C                some college      standard
4      male  group C                some college      standard
10     male  group C          associate's degree      standard
15   female  group C            some high school      standard
16     male  group C                 high school      standard
..      ...      ...                         ...           ...
979  female  group C          associate's degree      standard
984  female  group C            some high school      standard
986  female  group C          associate's degree      standard
996    male  group C                 high school  free/reduced
997  female  group C                 high school  free/reduced

    test preparation course  math score  reading score  writing score
1                 completed          69             90             88
4                      none          76             78             75
10                     none          58             54             52
15                     none          69             75             78
16                     none          88             89             86
..                      ...         ...            ...            ...
979                    none          91             95             94
984                    none          74             75             82
986                    none          40             59             51
996                    none          62             55             55
997               completed          59             71             65

[319 rows x 8 columns]
group D
     gender   groups parental level of education         lunch  \
8      male  group D                 high school  free/reduced
11     male  group D          associate's degree      standard
20     male  group D                 high school      standard
22     male  group D                some college      standard
24     male  group D           bachelor's degree  free/reduced
..      ...      ...                         ...           ...
989  female  group D                some college  free/reduced
992  female  group D          associate's degree  free/reduced
993  female  group D           bachelor's degree  free/reduced
998  female  group D                some college      standard
999  female  group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
8                 completed          64             64             67
11                     none          40             52             43
20                     none          66             69             63
22                     none          44             54             53
24                completed          74             71             80
..                      ...         ...            ...            ...
989               completed          67             86             83
992                    none          55             76             76
993                    none          62             72             74
998               completed          68             78             77
999                    none          77             86             86

[262 rows x 8 columns]
group E
     gender   groups parental level of education         lunch  \
32   female  group E             master's degree  free/reduced
34     male  group E                some college      standard
35     male  group E          associate's degree      standard
44   female  group E          associate's degree  free/reduced
50     male  group E                some college      standard
..      ...      ...                         ...           ...
962  female  group E          associate's degree      standard
968  female  group E          associate's degree      standard
987    male  group E            some high school      standard
990    male  group E                 high school  free/reduced
995  female  group E             master's degree      standard

    test preparation course  math score  reading score  writing score
32                     none          56             72             65
34                     none          97             87             82
35                completed          81             81             79
44                     none          50             56             54
50                     none          53             55             48
..                      ...         ...            ...            ...
962                    none         100            100            100
968                    none          68             76             67
987               completed          81             75             76
990               completed          86             81             75
995               completed          88             99             95

[140 rows x 8 columns]

In [38]:
data.grouby('groups').sum(numeric_only=True)

AttributeError: 'DataFrame' object has no attribute 'grouby'

In [ ]:
groups.min(numeric_only=True)

         math score  reading score  writing score
groups
group A          28             23             19
group B           8             24             15
group C           0             17             10
group D          26             31             32
group E          30             26             22

In [ ]:
groups.count() # This will count the number of non-null values in each group for each column.

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
groups,,,,,,,
group A,89,89,89,89,89,89,89
group B,190,190,190,190,190,190,190
group C,319,319,319,319,319,319,319
group D,262,262,262,262,262,262,262
group E,140,140,140,140,140,140,140

In [ ]:
# Find that groups which scored highest total in math score
groups=data.groupby("groups")

data.groupby("groups")["math score"].sum(numeric_only=True).sort_value()

AttributeError: 'Series' object has no attribute 'sort_value'

In [ ]:
#Find that group whcih scored min avg in writing
data.groupby("groups")["writing score"].mean(numeric_only=True).sort_values()

groups
group E    71.407143
Name: writing score, dtype: float64

In [ ]:
#Find the  parental level of education which has hghest total in reading score
data.groupby("paretalelvelfoeducation")["reading score"].sum(numeric_only=True).sort_values()

In [ ]:
#find the parental level of education which hashighestotalinreadinscore
data.groupby('parenta level of education').groups

KeyError: 'parenta level of education'

In [ ]:
#size()
data.groupby('parental levle of education').size()

KeyError: 'parental levle of education'